# Generated by Django 5.2.9 on 2025-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ph_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
