# Generated by Django 5.2.9 on 2025-12-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_student_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
