# Generated by Django 5.2.10 on 2026-01-09 08:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed in  course field', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed in name field', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ph_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number should contain only digits', regex='^\\d+$')]),
            preserve_default=False,
        ),
    ]
